# Generated by Django 4.1.5 on 2023-01-08 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Données',
        ),
        migrations.DeleteModel(
            name='Four',
        ),
    ]
