# Generated by Django 4.1.5 on 2023-01-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0002_delete_données_delete_four'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredients',
            name='eau',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='froment_T80',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='graines',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='levain',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='seigle_T170',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='sel',
            field=models.FloatField(default=0),
        ),
    ]
