# Generated by Django 4.1.5 on 2023-01-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0003_ingredients_eau_ingredients_froment_t80_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('T80', models.FloatField(default=0)),
                ('BuchNat', models.FloatField(default=0)),
                ('BuchMG', models.FloatField(default=0)),
                ('BuchRN', models.FloatField(default=0)),
                ('BuchNoix', models.FloatField(default=0)),
                ('RizSar', models.FloatField(default=0)),
                ('PetEp', models.FloatField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
