# Generated by Django 4.1.5 on 2023-01-08 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0004_data_delete_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='BuchMG',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='BuchNat',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='BuchNoix',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='BuchRN',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='PetEp',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='RizSar',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='data',
            name='T80',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
    ]
