# Generated by Django 4.1.5 on 2023-01-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0005_alter_data_buchmg_alter_data_buchnat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
