# Generated by Django 4.1.5 on 2023-01-13 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0006_alter_data_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('boulanger', models.CharField(default='', max_length=100, null='')),
            ],
        ),
        migrations.RemoveField(
            model_name='data',
            name='date',
        ),
        migrations.AddField(
            model_name='data',
            name='prod_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='prod.prod'),
        ),
    ]
