# Generated by Django 4.1.5 on 2023-01-13 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0007_prod_remove_data_date_data_prod_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='prod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.prod'),
        ),
    ]
