# Generated by Django 4.1.5 on 2023-01-14 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0008_alter_data_prod_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='Brioche',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='data',
            name='Cookies',
            field=models.IntegerField(default=0),
        ),
    ]
