# Generated by Django 4.1.5 on 2023-01-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0009_data_brioche_data_cookies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='Brioche',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='BuchMG',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='BuchNat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='BuchNoix',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='BuchRN',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='PetEp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='RizSar',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='data',
            name='T80',
            field=models.FloatField(default=0),
        ),
    ]
