# Generated by Django 4.1.5 on 2023-01-28 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0010_alter_data_brioche_alter_data_buchmg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FT80', models.FloatField(default=0)),
                ('ST170', models.FloatField(default=0)),
                ('PET80', models.FloatField(default=0)),
                ('RT80', models.FloatField(default=0)),
                ('SarT80', models.FloatField(default=0)),
                ('FPDT', models.FloatField(default=0)),
                ('eau', models.FloatField(default=0)),
                ('sel', models.FloatField(default=0)),
                ('oeufs', models.FloatField(default=0)),
                ('sucre', models.FloatField(default=0)),
                ('beurre', models.FloatField(default=0)),
                ('levain', models.FloatField(default=0)),
                ('raisin', models.FloatField(default=0)),
                ('noisettes', models.FloatField(default=0)),
                ('noix', models.FloatField(default=0)),
                ('graines', models.FloatField(default=0)),
                ('levure', models.FloatField(default=0)),
                ('four_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prod.data')),
            ],
        ),
    ]
