# Generated by Django 4.1.5 on 2023-01-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0011_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='four_pain',
            field=models.CharField(default='', max_length=50),
        ),
    ]
