# Generated by Django 4.1.5 on 2023-01-28 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prod', '0013_alter_recipe_four_pain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='four_pain',
            field=models.CharField(default='Brioche', max_length=50),
        ),
    ]
